### PR TITLE
Added mintty

### PR DESCRIPTION
**Pull request by shkm**
Did the best I could to get it looking somewhat similar to the iTerm/Terminal.app versions and based it mostly off the given colour palette.

I didn't include an image in the Readme as they're in another repo, but you could use the one attached here.

Thanks so much for your work on this colour scheme. I love it to pieces, and it's the first one I've really been bothered enough about to create a colour scheme for on my Windows box.

mintty

### CODE REVIEW

**Comment by JimmyMultani** [comment]
+1

Been using this on mintty for several weeks now and it works great.

**Comment by JimmyMultani** [comment]
Hey @shkm, can you please rebase this PR?

@zenorocha, if it's okay with you I'd like to maintain this as well. Thanks!

**Comment by zenorocha** [comment]
That would be awesome ;)

**Comment by JimmyMultani** [comment]
Hey @shkm, if you would be willing to recreate your PR request [here](https://github.com/dracula/atom), it would be greatly appreciated. Thanks!

**Comment by shkm** [comment]
Looks like this was already handled. Great work :-).

**Pull request closed without merging**
