### PR TITLE
Added theme for Sequel Pro

### PR DESCRIPTION
**Pull request by florianeckerstorfer**

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thanks @florianeckerstorfer and sorry for taking sooooo long to review this!

**Comment by zenorocha** [comment]
http://zenorocha.github.io/dracula-theme/sequel-pro/ :ghost:

**Comment by florianeckerstorfer** [comment]
Thanks for merging this. 🎉

**Pull request merged**
