### PR TITLE
Add GitHub Flavored Markdown support

### PR DESCRIPTION
**Pull request by ramonmcros**
Add GitHub Flavored Markdown support.

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
This looks pretty awesome @ramonmcros! Thanks!

There's only one minor thing that I think we should include. Syntax highlighting for grave accents that translates to `<code>`.

screen shot 2015-02-18 at 8 58 58 pm

Can you do that?

**Comment by ramonmcros** [comment]
Done :)

**Comment by ramonmcros** [comment]
I have added syntax highlighting for shell variables too.

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
https://github.com/zenorocha/dracula-theme/releases/tag/v0.7.6

**Pull request merged**
