### PR TITLE
Add gnome terminal gconf

### PR DESCRIPTION
**Pull request by benjamingarcia**
I extract gconf for gnome terminal

### CODE REVIEW

**Comment by nesl247** [comment]
Sorry for the delayed reply. Thanks for your submission though. Is this still good to go? If so, I'll create another repository under the new organization (https://github.com/dracula) where you can submit a PR against it to add the initial style.

Thanks!

**Comment by benjamingarcia** [comment]
well, I'm now under OS X, so I don't know if this PR, is already ok. I try this with a VM? for new organization, no problem. I began a theme for Nylas N1 too.

**Comment by nesl247** [comment]
@zenorocha How do you want to handle it? We probably shouldn't add it unless we have someone who wants to maintain it, and @benjamingarcia is now on OS X.

@benjamingarcia It's no problem at all. No need to get all crazy by doing a VM just for this. Thank you though!

**Comment by benjamingarcia** [comment]
and for Nylas n1?

**Comment by zenorocha** [comment]
I see... @benjamingarcia can you close this one and send a PR to https://github.com/dracula/nylas-n1?

**Comment by nesl247** [comment]
I'm going to close this since we won't really have a maintainer for gconf. For Nylas a repository has been created with most of the README's template filled in for you @benjamingarcia. We'll discuss more in the soon to be created PR.

Thanks! 😄

**Pull request closed without merging**
