### PR TITLE
Created a Coda version of Dracula

### PR DESCRIPTION
**Pull request by defectivebit**
Made a theme file for Panic's [Coda](http://panic.com/coda).

### CODE REVIEW

**Comment by zenorocha** [comment]
Thanks for contributing @defectivebit! Can you add some instructions on the README about how people can install it?

**Comment by defectivebit** [comment]
I'll update the readme with a screenshot and instructions but you just clone (or zip download) and double-click the .sss

**Comment by defectivebit** [comment]
I've added commits with the readme updates - I've noticed you host the screenshots at `http://zenorocha.github.io/dracula-theme/assets/img/screenshot-{{editor}}` so I've filled that in for the image url but could you please upload the screenshot:
screen shot 2015-09-02 at 21 39 25
Thanks

**Comment by zenorocha** [comment]
Merged! Thanks @defectivebit ;D

**Pull request merged**
