### PR TITLE
QtCreator syntax highlight

### PR DESCRIPTION
**Pull request by tewald**
Syntax style applied for QtCreator.
Just copy dracula.xml to:

* Linux:  `~/.config/QtProject/qtcreator/styles`
* Windows (7 and up): `Users\<user name>\AppData\Roaming\QtProject\qtcreator\styles`

Start (or restart) QtCreator and select the Dracula color scheme in the options dialog.

### CODE REVIEW

**Comment by nesl247** [comment]
Sorry for the delayed reply. Thanks for your submission though. Is this still good to go? If so, I'll create another repository under the new organization (https://github.com/dracula) where you can submit a PR against it to add the initial style.

Thanks!

**Comment by tewald** [comment]
Let me check and ping back on this! :-)

**Comment by tewald** [comment]
Yes, it's still good!

**Comment by zenorocha** [comment]
Awesome! Can you close this one and send a PR to https://github.com/dracula/qtcreator?

**Comment by tewald** [comment]
Sure!

**Comment by nesl247** [comment]
@tewald I create the initial commit with the README and such. Please update the Team section for yourself in your PR.

Thanks!

**Pull request closed without merging**
