### PR TITLE
Added generated theme for Visual Studio Code.

### LINKED ISSUE #106: Create theme for Visual Studio Code
Add support to **Visual Studio Code** is the new multiplatform text editor from Microsoft that can be used to develop with **NodeJS**, C++, ASP.NET, PHP, Python, Java.

https://code.visualstudio.com/

### PR DESCRIPTION
**Pull request by Ulthes**
Generated by converting TextMate theme through Yeoman Generator provided by Microsoft. Fixes #106

### CODE REVIEW

**Comment by Ulthes** [comment]
Obligatory screenshot:
screenshot_vscode

**Comment by zenorocha** [comment]
Hey @Ulthes, that's great! Could you also describe step by step how to install it? See http://zenorocha.github.io/dracula-theme/ for some examples.

**Comment by Ulthes** [comment]
Sure, no problem. I'll do it, once I get home from work :).

**Comment by Ulthes** [comment]
I have a question, should I make the description for how-to guide as a seperate pull request for gh-pages branch?

**Comment by zenorocha** [comment]
You can write it here and I move it there.

**Comment by Ulthes** [comment]
Ok, so I added a README file with instructions, later I will update the gh-pages and I have few questions:
- Where should I get the icon for VS Code?
- What about a screenshot? I see you are using Mac OS X screenshots and unfortunately I don't have one. I'd like to keep it consistent for your page with other editors. Plus I'd need the file you were opening in those editors.

**Comment by zenorocha** [comment]
http://zenorocha.github.io/dracula-theme/visual-studio-code

Thanks @Ulthes!!

**Pull request merged**
