### PR TITLE
Ulysses theme

### PR DESCRIPTION
**Pull request by defectivebit**
Wrote a port of Dracula to [Ulysses](http://ulyssesapp.com). I updated the README.md file with instructions on how to install the theme.

Screenshots:
screen shot 2015-10-28 at 21 08 14
img_0058

In order to keep with the patterns for the screenshot URLs, I pointed the screenshot URLs in the 
README file to http://zenorocha.github.io/dracula-theme/assets/img/screenshot-ulysses-mac.png and http://zenorocha.github.io/dracula-theme/assets/img/screenshot-ulysses-ipad.png

(note: GitHub doesn't seem to want to let me pull request my Ulysses commits without pull requesting my Coda commits, unfortunately. The Coda pull request is #101)

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @defectivebit, that's great!

Could you also describe step by step how to install it? See http://zenorocha.github.io/dracula-theme/ for some examples.

**Comment by defectivebit** [comment]
I added instructions to the README in 390a845 but the short version is either you can install the theme from the Ulysses website [here](http://styles.ulyssesapp.com/bundle/Dracula/56319778b634a4410207d126), which gives you the file you can double click on, or on a Mac you can clone the repository and double click the .ultheme file in the ulysses/ folder.

**Comment by zenorocha** [comment]
Gotcha!

**Comment by heinst** [comment]
@zenorocha just tested, the theme for Ulysses is good. We already have a Coda theme, so there is no need for it. @defectivebit can you remove the Coda theme please?

**Comment by defectivebit** [comment]
@heinst The coda theme on the Dracula webpage is the one I created, so I'm not sure what exactly you are asking me to do. Would you mind clarifying?

**Comment by heinst** [comment]
@defectivebit I cannot merge as the Coda theme in the pull request and the current one in the repository conflict. Could you remove the Coda theme from your pull request?

**Comment by zenorocha** [comment]
I figured out it would be better if I fixed the conflicts and merge it myself. Thanks a lot for reviewing @heinst and @defectivebit for creating this ;)

**Pull request merged**
