### PR TITLE
vim-airline version of Dracula theme

### PR DESCRIPTION
**Pull request by extrante**
Hi,

Wrote a somewhat subtle vim-airline theme that tries to fit well with dracula vim theme.

### CODE REVIEW

**Comment by film42** [comment]
Would you mind posting a screenshot of your changes?

**Comment by extrante** [comment]
dracula-airline

**Comment by taveras** [comment]
hah, did this a bit ago. yours is great though! ++

**Comment by taveras** [comment]
this is great!

**Comment by zenorocha** [comment]
Merged! Would you mind sending a PR with instructions on how to install it?

https://zenorocha.github.io/dracula-theme/vim/

**Pull request merged**
