### PR TITLE
Add Highlight Colours for Atom Editor find end replace

### PR DESCRIPTION
**Pull request by jacksaunders**
## Quick Gif showing colours, 
the colours are a lightened version of the selection colour to distinguish them easier

untitled

### CODE REVIEW

**Comment by zenorocha** [comment]
@JimmyMultani could you review an merge it?

**Comment by JimmyMultani** [comment]
Hey @jacksaunders, can you please rebase this PR? Thanks!

**Comment by jacksaunders** [comment]
@JimmyMultani Rebased 😎

**Comment by JimmyMultani** [comment]
@jacksaunders I don't think the rebase was done correctly. It just duplicated the styles back into `index.less`. Can you make the necessary changes inside `styles/base.less`?

Thanks!

**Comment by jacksaunders** [comment]
ah yea sorry about that all in the correct place now @JimmyMultani

**Comment by JimmyMultani** [comment]
Awesome, thank you! :)

**Pull request merged**
