### PR TITLE
Visual Studio

### PR DESCRIPTION
**Pull request by epidemicz**
Hi, I created a Dracula vssettings theme for Visual Studio and I would greatly appreciate it if you took the time to take a look at it.  Please forgive me if I am doing something incorrectly as I am a novice when it comes to contributing on github.  

I believe this will be compatible with many versions of Visual Studio, if you check it out on studiostyl.es, you have the option to download it for many different versions and you can see a very detailed preview.  http://studiostyl.es/schemes/dracula-1

Thanks!

## Visual Studio

studiostyle

### Preview/Download at studiostyl.es 

http://studiostyl.es/schemes/dracula-1

### Installing

1. In Visual Studio, choose Tools > Import and Export Settings
2. Choose Import Selected Environment Settings and select whether you want to back up your existing settings or not
3. Click Browse... to choose the file you downloaded.
4. You get a choice which settings you want to import - choose all of them since the file only contains color settings and won't touch your other VS settings.
5. Click Finish and you'll see the new colors.

### CODE REVIEW

**Comment by zenorocha** [comment]
http://zenorocha.github.io/dracula-theme/visual-studio-code

**Comment by taiar** [comment]
Wow, the site is really nice! :+1: 

Thanks, @zenorocha!

**Comment by epidemicz** [comment]
Zeno, I see you added the visual studio code theme, but it looks like you never merged in this one? :( 

I don't normally use Visual Studio Code, but I had a quick look and it does appear to use a different format.

**Comment by Ulthes** [comment]
@epidemicz Yes, Visual Studio Code uses different format. Visual Studio != Visual Studio Code, so @zenorocha still needs to merge this one for official Visual Studio theme.

**Comment by simkessy** [comment]
Any update on this, would love to use this is VS

**Comment by Ulthes** [comment]
@simkessy You can at this time download it at http://studiostyl.es/schemes/dracula-1 as @epidemicz wrote in his first comment. I keep using it at work all the time. Not sure why @zenorocha didn't merged it, yet...

**Comment by zenorocha** [comment]
Aaaand it's merged ;)

Still need to work on instructions and screenshot for this, but thanks @epidemicz and sorry for taking so long to merge it.

**Pull request merged**
