### PR TITLE
New faces for Gnus group/summary views

### PR DESCRIPTION
**Pull request by dinojr**
I just added some faces configurations for the Summary and Group views in Gnus. The gnus-summary-markup-face is a custom one used in my setup for the summary line format.

### CODE REVIEW

**Comment by zenorocha** [comment]
@avelino could you help me with this one?

**Comment by film42** [comment]
@dinojr Could you post a screenshot?

**Comment by dinojr** [comment]
Sure, here it is
dracula-screenchot

**Comment by film42** [comment]
Awesome! Thanks for doing that. I think this is a great addition. I'll get this released tomorrow.

**Comment by zenorocha** [comment]
lol thanks @dinojr & @film42

**Comment by avelino** [comment]
+1, very very good!

**Comment by film42** [comment]
@zenorocha Do you want me to bump all versions to `1.2.1` or just emacs?

**Pull request merged**
