### PR TITLE
New Slack theme.

### PR DESCRIPTION
**Pull request by quagliato**
New slack theme, as discussed on issue #87 .

### CODE REVIEW

**Comment by BrandonMathis** [comment]
Looks fantastic here!

screen shot 2015-09-30 at 11 45 15 am

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/zenorocha/dracula-theme/compare/d6b47ee~1...d6b47ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thanks @quagliato and sorry for the delay on merging it!

**Comment by zenorocha** [comment]
http://zenorocha.github.io/dracula-theme/slack/

**Comment by quagliato** [comment]
Thanks, man! ;)

-- eduardo quagliato
http://quagliato.me

2015-10-31 21:39 GMT-02:00 Zeno Rocha <notifications@github.com>:

**Comment by quagliato** [comment]
Thanks, man! ;)

**Pull request closed without merging**
