### PR TITLE
An attempt at a Dracula Sublime Text UI theme

### PR DESCRIPTION
**Pull request by ghost**
default-configuration

This is my attempt at creating a Sublime Text UI theme that fits in with the awesome syntax color scheme. I'm not a user interface designer, so any feedback is welcomed. There are a few more screenshots at the bottom of the pull request that illustrate its customization options.

Interested in merging this? I've coded it up such that it should fit into the Dracula Color Scheme Sublime package.

### CODE REVIEW

**Comment by cheniel** [comment]
This is awesome! Thanks for making this.

**Comment by heinst** [comment]
@zenorocha We already have a Sublime Text theme, should this be closed?

**Comment by cheniel** [comment]
This is a UI Theme (styles tabs, sidebar, etc). Right now only a Syntax Theme is offered.

**Comment by jacksaunders** [comment]
@zenorocha I Have merged the patch for this pull request, need to update the readme as the PR uses the outdated one, have reviewed and is working good, could do with some small styling tweaks but otherwise is looking good

**Comment by zenorocha** [comment]
Closing this one for now since we're moving everything to a separate repo, but let's definitely revisit this. I really liked this approach https://atom.io/themes/dracula-ui :)

**Pull request closed without merging**
