### PR TITLE
Emacs Love

### PR DESCRIPTION
**Pull request by film42**
This adds my port of the dracula theme for Emacs.

Issue with discussion: #93 

I added a link to a screenshot in the README, but you're probably going to want to add that to all the other assets and update the URL.

NOTE: I will need to make a PR to [MELPA](https://github.com/milkypostman/melpa) to add the following recipe to `recipes/dracula-theme`.

```elisp
(dracula-theme :fetcher github
               :repo "zenorocha/dracula-theme"
               :files ("emacs/*.el"))
```

edit: typos

### CODE REVIEW

**Comment by film42** [comment]
Any love?

**Comment by tkaczu** [comment]
Hi,

Could anybody please merge this emacs theme to the repo?

**Comment by avelino** [comment]
added in melpa.org (very very easy)

**Comment by film42** [comment]
I'll merge master in to clean this up later today.

**Comment by avelino** [comment]
@film42 

the theme was good for emacs (GUI), in terminal doesn't work!

**Comment by film42** [comment]
@avelino That is a problem, but there's not much we can do until emacs supports 16bit color in the terminal.

Btw, since the README changed to move docs to the website, here's what I had written since merging master will override my changes:

Instructions from README:

## Emacs

Emacs Preview

#### Activating the theme

Install using MELPA

```
M-x package-install <RET> dracula-theme
```

#### Install manually

Add the emacs theme files to `~/.emacs.d/themes`.

To load a theme add the following to your init.el

```elisp
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
(load-theme 'dracula t)
```

**Comment by zenorocha** [comment]
You did an amazing job @film42, that was the best PR I received on this repo ;D

Would you think of being added to [the team](https://github.com/zenorocha/dracula-theme#team) as an official maintainer for this Emacs theme?

**Comment by film42** [comment]
Thanks @zenorocha ! Sure, I can maintain the emacs theme :)

**Pull request merged**
