### PR TITLE
Adds tmux theme

### PR DESCRIPTION
**Pull request by BrandonMathis**
I use tmux a lot so I added a tmux theme for dracula
screen shot 2015-09-29 at 9 53 37 pm

### CODE REVIEW

**Comment by BrandonMathis** [comment]
The example tmux config is also cock full of a bunch of tmux configs that I use. I'd be cool with removing them and slimming this down to theme only if you guys are interested in having a tmux theme for dracula :)

**Comment by zenorocha** [comment]
Hey @BrandonMathis, that's awesome! Could you add instructions on how to install it as well?

**Comment by BrandonMathis** [comment]
I sure will!

**Comment by zenorocha** [comment]
Cool!

**Comment by BrandonMathis** [comment]
Ugh, I cant seem to get this working as an isolated set of configs. Gonna re-submit this later with some reasonable docs in the readme on how to install

**Comment by zenorocha** [comment]
No problem ;)

**Pull request closed without merging**
