### PR TITLE
Follow Atom Syntax standards

### PR DESCRIPTION
**Pull request by JimmyMultani**
Hey @zenorocha!

I noticed that your syntax theme did not work on a few themes that are widely used on Atom.

This pull request should fix issue #81 as it now follow Atom's syntax requirements for themes.

Hopefully, you can test this out soon! :)

### CODE REVIEW

**Comment by film42** [comment]
Looks like you need to rebase this branch.

**Comment by JimmyMultani** [comment]
Rebased. :)

**Comment by zenorocha** [comment]
@JimmyMultani go ahead and merge it ;)

**Comment by zenorocha** [comment]
🎉

**Pull request merged**
